Title = "Leetcode"
ReportCard = true
Description = '''
This is a home for attempts at Leetcode problems in Go. I wouldn't recommend using these as an answer key.
I primarily use Leetcode problems as a way to get better at writing tests for weird edge cases.
But hey, trying out new algorithms is fun too.
'''

[Sections]

[Sections.Documentation]
Title = "Documentation"
Body = '''
Update the readme with available packages with `go run main.go`
'''

[Sections.Disclaimer]
Title = "Disclaimer"
Emoji = ":loudspeaker:"
Body = '''
These are by no means the absolute right answers, and many of them will likely be incomplete.
But they sure are a compilation of me giving it the ol' college try.
So if they help you, awesome! If not, sorry in advance on that one, friend.
'''

[Packages]

[Packages.atoi]
Title = "atoi"
Description = "Converting strings to integers."
Path = "pkg/atoi"

[Packages.lower]
Title = "lower"
Description = "Converting strings to lowercase using goroutines and channels."
Path = "pkg/lower"

[Packages.maxones]
Title = "maxones"
Description = "Finding the max consecutive ones possible given the provided constraints."
Path = "pkg/maxones"

[Packages.mostcandies]
Title = "mostcandies"
Description = "[Find the kid with the most candies](https://leetcode.com/problems/kids-with-the-greatest-number-of-candies/)"
Path = "pkg/mostcandies"

[Packages.perimeter]
Title = "perimeter"
Description = "Given an array A of positive lengths, return the largest perimeter of a triangle with non-zero area, formed from 3 of these lengths."
Path = "pkg/perimeter"

[Packages.reversint]
Title = "reversint"
Description = "Reverse an integer. Featuring: a bunch of weird edge cases in the conditions."
Path = "pkg/reversint"

[Packages.ringbuffer]
Title = "ringbuffer"
Description = "Implementing a ring buffer to perform queing with a capacity limit."
Path = "pkg/ringbuffer"

[Packages.runningsum]
Title = "runningsum"
Description = "[Getting the running sum of a 1d array](https://leetcode.com/problems/running-sum-of-1d-array/)"
Path = "pkg/runningsum"
