name: Lint

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - id: 1
        name: Check with golangci-lint
        uses: actions-contrib/golangci-lint@v1
