name: test
on:
  push:
    tags:
      - v*
    branches:
      - *
  pull_request:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: go test -v ./...
